--[Boosting of single classifier] Find the misclassified samples from TrainSet, and increase their weights (e.g., by simply duplicating them) to implement the boosting step. Repeat steps 5 and 6 above but but stop as soon you see the accuracy stop improving

CONNECT TO DBKB;
--misclassified row numbers
--create NBC BOOSTING table which stores the predicted value and actual train data values

DROP TABLE NBC_BOOSTING;

CREATE TABLE NBC_BOOSTING("PID" INTEGER,"PREDICTED_DECISION" VARCHAR(20),"TEST_DATA_DECISION" VARCHAR(20));

INSERT INTO NBC_BOOSTING
WITH TEMP1 AS(
SELECT PID,COLUMNNO,ATT,P.DECISION AS PROBABLE_DECISION FROM TRAINDATA, PROBABILITY_CLASS_LABELS AS P ORDER BY PID
), 
TEMP2 AS(
SELECT PID,T1.COLUMNNO,T1.ATT,DECISION,PROBABILITY FROM TEMP1 AS T1 INNER JOIN PROBABILITY_ATTR_VALUES AS P ON P.COLUMNNO=T1.COLUMNNO AND P.ATT=T1.ATT
),
TEMP4 AS(
SELECT DISTINCT * FROM TEMP2
),
TEMP3 AS(
SELECT SUM(LOG(PROBABILITY)) AS PROBS,PID,DECISION FROM TEMP4 GROUP BY DECISION,PID
),
TEMP5 AS(
--ADD CLASS LABELS'S PROBABILITY TO THESE VALUES
SELECT (PROBS+LOG(PROBABILITY)) AS FINAL_PROB,PID,T3.DECISION  FROM TEMP3 AS T3,PROBABILITY_CLASS_LABELS AS P WHERE T3.DECISION=P.DECISION
),
TEMP6 AS(
-- NOW WE FIND MAX OF THESE VALUES WHICH BECOME OUR PREDICTION
SELECT MAX(FINAL_PROB) AS PROB,PID FROM TEMP5 GROUP BY PID
),
TEMP7 AS(
--WE GET PREDICTED DECISION
SELECT T5.PID,T5.DECISION FROM TEMP5 AS T5, TEMP6 AS T6 WHERE T5.PID=T6.PID AND T5.FINAL_PROB=T6.PROB
),
TEMP9 AS(
--THIS HAS ALL THE ACTUAL DATASET
SELECT DISTINCT PID, DECISION FROM TRAINDATA ORDER BY PID
),
TEMP8 AS(
SELECT T7.PID,T7.DECISION AS PREDICTED_DECISION, T9.DECISION AS TEST_DATA_DECISION FROM TEMP7 AS T7, TEMP9 AS T9 WHERE T7.PID=T9.PID
)
SELECT * FROM TEMP8;

--DOUBLE THE WEIGHT FOR THE ERROR ROWS IN TRAINDATA

INSERT INTO TRAINDATA(COLUMNNO,ATT,DECISION) SELECT COLUMNNO,ATT,DECISION FROM TRAINDATA WHERE PID IN (SELECT PID FROM NBC_BOOSTING WHERE PREDICTED_DECISION!=TEST_DATA_DECISION);

TERMINATE;




