
CREATE OR REPLACE PROCEDURE GET_ACCURACY_NBC(OUT total_rows DECIMAL,OUT accurate_rows DECIMAL,OUT accuracy DECIMAL)
BEGIN


--CALCULATE ACCURACY
SELECT COUNT(PID) INTO accurate_rows FROM NBC WHERE PREDICTED_DECISION=TEST_DATA_DECISION;

SELECT DECIMAL(COUNT(DISTINCT PID)) INTO total_rows FROM TESTDATA;

SET accuracy=(accurate_rows/total_rows)*100;

END@
