
CREATE OR REPLACE PROCEDURE GET_ACCURACY_1R_TREE(OUT total_rows DECIMAL, OUT accurate_rows DECIMAL, OUT accuracy Decimal(18, 13))
BEGIN


SELECT DECIMAL(COUNT(DISTINCT T.PID)) INTO accurate_rows FROM  TESTDATA AS T , SPLIT_ATTR AS S, FREQUENT_CLASS AS F WHERE T.COLUMNNO=S.COLNO AND F.COLUMNNO=S.COLNO AND T.COLUMNNO=F.COLUMNNO AND T.ATT=F.ATT AND T.DECISION=F.DECISION;

SELECT DECIMAL(COUNT(DISTINCT PID)) INTO total_rows FROM TESTDATA;

SET accuracy=(accurate_rows/total_rows)*100;

END@


